gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"

gText_Pie_Welcome::
	.string "Oh, wait!\p"
	.string "Before you go, a message from this\n"
	.string "hack's creator: MinZe\p"
	.string "Welcome to Pokémon Nuzlocke Emerald!\p"
	.string "This is a hack that only adds\n"
	.string "nuzlocke options to the existing\l"
	.string "mechanics!\p"
	.string "Before you get started, you'll need\n"
	.string "to choose your settings.Be careful!\l"
	.string "Those cannot be changed!\p"
	.string "If you need help, check the existing\n"
	.string "documentation for each choice.$"

gText_Pie_NormalMode::
	.string "In Normal Mode, Trainers won't have\n"
	.string "EVs, so you won't need to worry\l"
	.string "about your own Pokémon's stats.\p"
	.string "This difficulty is recommended if\n"
	.string "you're new to difficulty hacks, or\l"
	.string "if you don't want to deal with EVs.\p"
	.string "So, would you like to play on\n"
	.string "Normal Mode?$"

gText_Pie_HardMode::
	.string "In Hard Mode, Trainers will have EV-\n"
	.string "trained Pokémon, so you might\l"
	.string "want to EV train your own team.\p"
	.string "You can do this passively - no\n"
	.string "grinding required - so don't let that\l"
	.string "put you off!\p"
	.string "This difficulty is recommended for\n"
	.string "experienced players.\p"
	.string "So, would you like to play on\n"
	.string "Hard Mode?$"

gText_Pie_ChallengeMode::
	.string "Like Hard Mode, Trainers in Challenge\n"
	.string "Mode have EV trained teams.\p"
	.string "It also adds two restrictions:\p"
	.string "You can't access the bag in Trainer\n"
	.string "Battles, and the Shift battle style is\l"
	.string "disabled.\p"
	.string "That means you'll follow the same rules\n"
	.string "as your opponents, so good strategy\l"
	.string "and a balanced team are more important\l"
	.string "in this mode.\p"
	.string "This difficulty is only recommended if\n"
	.string "it sounds appealing to you!\p"
	.string "So, would you like to play on\n"
	.string "Challenge Mode?$"

gText_Pie_WhichDifficulty::
	.string "If you need help, check the existing\n"
    .string "documentation for each choice.$"

gText_Pie_Documents::
	.string "Great! If you want more information,\n"
	.string "please check the documents that came\l"
	.string "with the hack's patch.\p"
	.string "They cover everything from Pokémon and\n"
	.string "item locations to new ability effects.\p"
	.string "Finally, I hope you enjoy the hack!\n"
	.string "- Buffel Saft\p"
	.string "$"
